### ISSUE TITLE
Use JOption  pane

### ISSUE THREAD

**Issue by JoeCol29** [jethalal7777/Java-answers#2]
Write the class definition for a circle that has one instance variable (attribute) for the radius. 
The class must have 2 constructors (one is the default, and the other has one argument).
Also define appropriate get-and-set methods, as well as methods to return the diameter, circumference, and area of a circle.
Use the math class for calculations where possible.
Write another class that contains a main method in which you use both constructors to construct 2 circle objects. 
Use the JOptionpane class to get the radius for each of the objects.
Call the appropriate methods to display the radius, diameter, circumference and area of each object. 
Use the JOptionpane class to display the values

**Comment by mevivek1898** [comment]
Ok
